
server:
  port: 8080

spring:
  application:
    name: download
  r2dbc:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

rapidapi:
  key: ${RAPIDAPI_KEY}
  host: ${RAPIDAPI_HOST}
  base-url: https://social-media-video-downloader.p.rapidapi.com


