spring:
  application:
    name: donwload
  r2dbc:
    url: r2dbc:postgresql://aws-0-us-east-1.pooler.supabase.com:5432/postgres
    username: postgres.aaqdicjpmdxudtixqfic
    password: 66LwnnFOEwZPOWyg
  server:
    port: 8080
